package nc.vo.to.settlerule.entity;

/**
 * 功能说明: 基于SmartVO的业务VO.结算规则子表,
 * 调试时可以使用nc.vo.scm.bd.SmartVODataUtils.expose()展示其数据。 Generated By CodeSeed 3.1
 * 修改记录： 修改人, 日期, 说明
 */
import nc.vo.pub.IVOMeta;
import nc.vo.pub.SuperVO;
import nc.vo.pub.lang.UFBoolean;
import nc.vo.pub.lang.UFDateTime;
import nc.vo.pub.lang.UFDouble;
import nc.vo.pubapp.pattern.model.meta.entity.vo.VOMetaFactory;

public class SettleRuleBVO extends SuperVO {
	// 暂估成本是否自动暂估应付
	public static final String BINAUTOESTIMATEAP = "binautoestimateap";

	// 入库是否自动暂估成本
	public static final String BINAUTOESTIMATEIA = "binautoestimateia";

	// 询价后价格是否可改
	public static final String BMODIFYPRICE = "bmodifyprice";

	// 出库签字是否自动传存货
	public static final String BOUTAUTOPUSHIA = "boutautopushia";

	// 出库签字是否自动作发出商品
	public static final String BOUTAUTOSENDOUT = "boutautosendout";

	// 是否传应收应付
	public static final String BPUSHARAP = "bpusharap";

	// 调拨物料分类
	public static final String CINVBASCLASS = "cinvbasclass";

	// 调拨物料
	public static final String CINVENTORYID = "cinventoryid";

	// 子表主键
	public static final String CSETTLERULE_BID = "csettlerule_bid";

	// 结算规则主表_主键
	public static final String CSETTLERULEID = "csettleruleid";

	// 出库传应收规则
	public static final String FOUTTOARRULE = "fouttoarrule";

	// 加价率
	public static final String NADDPRICERATE = "naddpricerate";

	// 集团
	public static final String PK_GROUP = "pk_group";

	/**
   * 
   */
	private static final long serialVersionUID = -8425159802200717242L;

	// 时间戳
	public static final String TS = "ts";

	// 暂估取价规则
	public static final String VESTIMATEPRICERULE = "vestimatepricerule";

	// 价格规则
	public static final String VPRICERULE = "vpricerule";

	// 加价额 gwj
	public static final String NADDPRICEVALUE = "naddpricevalue";

	public UFBoolean getBinautoestimateap() {
		return (UFBoolean) this
				.getAttributeValue(SettleRuleBVO.BINAUTOESTIMATEAP);
	}

	public UFBoolean getBinautoestimateia() {
		return (UFBoolean) this
				.getAttributeValue(SettleRuleBVO.BINAUTOESTIMATEIA);
	}

	public UFBoolean getBmodifyprice() {
		return (UFBoolean) this.getAttributeValue(SettleRuleBVO.BMODIFYPRICE);
	}

	public UFBoolean getBoutautopushia() {
		return (UFBoolean) this.getAttributeValue(SettleRuleBVO.BOUTAUTOPUSHIA);
	}

	public UFBoolean getBoutautosendout() {
		return (UFBoolean) this
				.getAttributeValue(SettleRuleBVO.BOUTAUTOSENDOUT);
	}

	public UFBoolean getBpusharap() {
		return (UFBoolean) this.getAttributeValue(SettleRuleBVO.BPUSHARAP);
	}

	public String getCinvbasclass() {
		return (String) this.getAttributeValue(SettleRuleBVO.CINVBASCLASS);
	}

	public String getCinventoryid() {
		return (String) this.getAttributeValue(SettleRuleBVO.CINVENTORYID);
	}

	public String getCsettlerule_bid() {
		return (String) this.getAttributeValue(SettleRuleBVO.CSETTLERULE_BID);
	}

	public String getCsettleruleid() {
		return (String) this.getAttributeValue(SettleRuleBVO.CSETTLERULEID);
	}

	public Integer getFouttoarrule() {
		return (Integer) this.getAttributeValue(SettleRuleBVO.FOUTTOARRULE);
	}

	@Override
	public IVOMeta getMetaData() {
		IVOMeta meta = VOMetaFactory.getInstance().getVOMeta(
				"to.to_settlerule_b");
		return meta;
	}

	public UFDouble getNaddpricerate() {
		return (UFDouble) this.getAttributeValue(SettleRuleBVO.NADDPRICERATE);
	}

	public String getPk_group() {
		return (String) this.getAttributeValue(SettleRuleBVO.PK_GROUP);
	}

	public UFDateTime getTs() {
		return (UFDateTime) this.getAttributeValue(SettleRuleBVO.TS);
	}

	public String getVestimatepricerule() {
		return (String) this
				.getAttributeValue(SettleRuleBVO.VESTIMATEPRICERULE);
	}

	public String getVpricerule() {
		return (String) this.getAttributeValue(SettleRuleBVO.VPRICERULE);
	}

	public void setBinautoestimateap(UFBoolean binautoestimateap) {
		this.setAttributeValue(SettleRuleBVO.BINAUTOESTIMATEAP,
				binautoestimateap);
	}

	public void setBinautoestimateia(UFBoolean binautoestimateia) {
		this.setAttributeValue(SettleRuleBVO.BINAUTOESTIMATEIA,
				binautoestimateia);
	}

	public void setBmodifyprice(UFBoolean bmodifyprice) {
		this.setAttributeValue(SettleRuleBVO.BMODIFYPRICE, bmodifyprice);
	}

	public void setBoutautopushia(UFBoolean boutautopushia) {
		this.setAttributeValue(SettleRuleBVO.BOUTAUTOPUSHIA, boutautopushia);
	}

	public void setBoutautosendout(UFBoolean boutautosendout) {
		this.setAttributeValue(SettleRuleBVO.BOUTAUTOSENDOUT, boutautosendout);
	}

	public void setBpusharap(UFBoolean bpusharap) {
		this.setAttributeValue(SettleRuleBVO.BPUSHARAP, bpusharap);
	}

	public void setCinvbasclass(String cinvbasclass) {
		this.setAttributeValue(SettleRuleBVO.CINVBASCLASS, cinvbasclass);
	}

	public void setCinventoryid(String cinventoryid) {
		this.setAttributeValue(SettleRuleBVO.CINVENTORYID, cinventoryid);
	}

	public void setCsettlerule_bid(String csettlerule_bid) {
		this.setAttributeValue(SettleRuleBVO.CSETTLERULE_BID, csettlerule_bid);
	}

	public void setCsettleruleid(String csettleruleid) {
		this.setAttributeValue(SettleRuleBVO.CSETTLERULEID, csettleruleid);
	}

	public void setFouttoarrule(Integer fouttoarrule) {
		this.setAttributeValue(SettleRuleBVO.FOUTTOARRULE, fouttoarrule);
	}

	public void setNaddpricerate(UFDouble naddpricerate) {
		this.setAttributeValue(SettleRuleBVO.NADDPRICERATE, naddpricerate);
	}

	public void setPk_group(String pk_group) {
		this.setAttributeValue(SettleRuleBVO.PK_GROUP, pk_group);
	}

	public void setTs(UFDateTime ts) {
		this.setAttributeValue(SettleRuleBVO.TS, ts);
	}

	public void setVestimatepricerule(String vestimatepricerule) {
		this.setAttributeValue(SettleRuleBVO.VESTIMATEPRICERULE,
				vestimatepricerule);
	}

	public void setVpricerule(String vpricerule) {
		this.setAttributeValue(SettleRuleBVO.VPRICERULE, vpricerule);
	}

	public UFDouble getNaddpricevalue() {
		return (UFDouble) this.getAttributeValue(SettleRuleBVO.NADDPRICEVALUE);
	}

	public void setNaddpricevalue(UFDouble naddpricevalue) {
		this.setAttributeValue(SettleRuleBVO.NADDPRICEVALUE, naddpricevalue);
	}

}
